# Generated by Django 5.2.12 on 2026-04-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('course', 'Course Article'), ('chapter', 'Chapter Article'), ('open', 'Open Article')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='courses.course'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
