# Generated by Django 5.2.12 on 2026-04-06 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_stream_id', models.CharField(max_length=255, unique=True)),
                ('youtube_broadcast_id', models.CharField(max_length=255, unique=True)),
                ('stream_key', models.CharField(max_length=255)),
                ('rtmp_url', models.URLField(max_length=500)),
                ('watch_url', models.URLField(max_length=500)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_stream_sessions', to='courses.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='live_stream_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'is_live'], name='livestreams_teacher_668f02_idx'), models.Index(fields=['course', 'is_live'], name='livestreams_course__09017c_idx'), models.Index(fields=['youtube_stream_id'], name='livestreams_youtube_116c0a_idx'), models.Index(fields=['youtube_broadcast_id'], name='livestreams_youtube_940621_idx')],
            },
        ),
    ]
